#!/bin/sh

set -e

sync () {
    echo "==== Pushing changes ===="
    git add .
    git commit -m "$(date)"
    git push -u origin master
    echo "==== done ===="
}

if [[ "$1" = "sync" ]]; then
    sync
else
    pushd ~/dotfiles
    make $1
    sync
    popd
fi
