#!/bin/sh

set -e

sync () {
    git add .
    git commit -m "$(date)"
    git push -u origin master
}

if [[ "$1" = "sync" ]]; then
    sync
else
    pushd ~/dotfiles
    make $1
    sync
    popd
fi
