background_opacity: 0.94

selection:
  save_to_clipboard: true

font:
  size: 9
  normal:
    family: "JetBrains Mono"
       
  offset:
    y: -4

window:
  padding:
    x: 10
    y: 10

import:
  - /home/theocodes/.config/alacritty/molokai.yml
